services:
  user-service:
    image: ${DOCKERHUB_USERNAME}/taskflow-user-service:latest
    container_name: user-service
    restart: always
    environment:
      JAVA_TOOL_OPTIONS: "-Xms128m -Xmx256m"
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-user:5432/${USER_DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${USER_DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${USER_DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
    networks:
      - taskflow-network

  task-service:
    image: ${DOCKERHUB_USERNAME}/taskflow-task-service:latest
    container_name: task-service
    environment:
      JAVA_TOOL_OPTIONS: "-Xms128m -Xmx256m"
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-task:5432/${TASK_DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${TASK_DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${TASK_DB_PASSWORD}
    networks:
      - taskflow-network

  api-gateway:
    image: ${DOCKERHUB_USERNAME}/taskflow-api-gateway:latest
    container_name: api-gateway
    ports:
      - "9090:9090"
    environment:
      JAVA_TOOL_OPTIONS: "-Xms128m -Xmx256m"
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - user-service
      - task-service
    networks:
      - taskflow-network
        
networks:
  taskflow-network:
    external: true




