CREATE DATABASE IF NOT EXISTS user_db;
CREATE DATABASE IF NOT EXISTS task_db;

CREATE USER IF NOT EXISTS 'taskflow_app'@'%' IDENTIFIED BY 'PLACEHOLDER_PASSWORD';

GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, INDEX, ALTER ON user_db.* TO 'taskflow_app'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, INDEX, ALTER ON task_db.* TO 'taskflow_app'@'%';

FLUSH PRIVILEGES;